package com.fernandaazevedo.common;

import com.fernandaazevedo.domain.*;
import jakarta.servlet.http.HttpSession;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.*;

@RestController @RequestMapping("/api")
public class ApiController {
  private final DemoService d; private static final Set<String> BLOCKED=Set.of("exe","msi","bat","cmd","com","scr","ps1","vbs","js","jar","apk","dll","sh","iso");
  public ApiController(DemoService d){this.d=d;}
  @GetMapping("/public/settings") public Map<String,Object> settings(){return d.payload(d.records.findByTypeOrderByCreatedAtDesc("SETTING").get(0));}
  @GetMapping("/public/campaigns") public List<Map<String,Object>> campaigns(){return rows("CAMPAIGN",null).stream().filter(x->x.get("status").equals("PUBLISHED")).toList();}
  @GetMapping("/{type}") public ResponseEntity<?> list(@PathVariable String type,HttpSession s){AppUser u=user(s);if(u==null)return unauthorized();String t=mapType(type);boolean allowed=u.role.equals("ADMIN")||(type.equals("users")&&u.permissions.contains("users.view"))||(type.equals("consents")&&u.permissions.contains("consents.view_status"));if(Set.of("users","audits","consents","campaigns").contains(type)&&!allowed&&!type.equals("campaigns"))return forbidden();if(type.equals("users"))return ResponseEntity.ok(d.users.findAll().stream().map(this::userView).toList());return ResponseEntity.ok(rows(t,(u.role.equals("PATIENT")||u.role.equals("DOCTOR"))&&!type.equals("campaigns")?u.email:null));}
  @PostMapping("/appointments/checkout") public ResponseEntity<?> checkout(HttpSession s){AppUser u=user(s);if(u==null)return unauthorized();var cfg=settings();var r=d.save("APPOINTMENT",u.email,"PAYMENT_PENDING","FA-CONS-"+System.currentTimeMillis(),Map.of("patient",u.name,"doctor","Aguardando definição","priceAtPurchase",cfg.get("consultationPrice"),"doctorPayoutAtPurchase",cfg.get("doctorBasePayout")));return ResponseEntity.ok(row(r));}
  @PostMapping("/appointments/{id}/payment/mock-approve") public ResponseEntity<?> approve(@PathVariable Long id,HttpSession s){return updateOwned(id,s,"PAID",Map.of("payment","APPROVED"));}
  @PutMapping("/appointments/{id}/pre-anamnesis") public ResponseEntity<?> anamnesis(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpSession s){return updateOwned(id,s,"ANAMNESIS_COMPLETED",Map.of("anamnesis",b,"version",1));}
  @PostMapping("/records/{type}") public ResponseEntity<?> create(@PathVariable String type,@RequestBody Map<String,Object>b,HttpSession s){AppUser u=user(s);if(u==null)return unauthorized();String t=mapType(type);if(Set.of("CAMPAIGN","SETTING").contains(t)&&!u.role.equals("ADMIN"))return forbidden();if(t.equals("USER")&&!u.role.equals("ADMIN")&&!u.permissions.contains("users.create"))return forbidden();if(t.equals("USER")){AppUser n=new AppUser();n.name=String.valueOf(b.get("name"));n.email=String.valueOf(b.get("email"));n.role=String.valueOf(b.getOrDefault("role","PATIENT"));n.passwordHash=d.encoder.encode("Temporaria@123");n.temporaryPassword=true;d.users.save(n);d.audit(u.email,"USER_CREATED","USER",null,n.email);return ResponseEntity.ok(userView(n));}var r=d.save(t,String.valueOf(b.getOrDefault("owner",u.email)),String.valueOf(b.getOrDefault("status","OPEN")),String.valueOf(b.getOrDefault("reference",t+"-"+System.currentTimeMillis())),b);d.audit(u.email,t+"_CREATED",t,null,r.reference);return ResponseEntity.ok(row(r));}
  @PutMapping("/admin/settings/commercial") public ResponseEntity<?> commercial(@RequestBody Map<String,Object>b,HttpSession s){AppUser u=user(s);if(u==null||!u.role.equals("ADMIN"))return forbidden();Object before=settings();d.save("SETTING","PUBLIC","ACTIVE","commercial",b);d.audit(u.email,"COMMERCIAL_SETTING_UPDATED","SETTING",before,b);return ResponseEntity.ok(b);}
  @PostMapping("/records/{id}/status") public ResponseEntity<?> status(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpSession s){AppUser u=user(s);if(u==null)return unauthorized();var r=d.records.findById(id).orElse(null);if(r==null)return ResponseEntity.notFound().build();if(r.type.equals("CAMPAIGN")&&!u.role.equals("ADMIN"))return forbidden();if(r.type.equals("TICKET")&&!u.role.equals("ADMIN")&&!u.permissions.contains("support.tickets.close"))return forbidden();String before=r.status;r.status=String.valueOf(b.get("status"));r.updatedAt=java.time.LocalDateTime.now();d.records.save(r);d.audit(u.email,r.type+"_STATUS_CHANGED",r.reference,before,r.status);return ResponseEntity.ok(row(r));}
  @PostMapping("/upload") public ResponseEntity<?> upload(@RequestParam MultipartFile file,HttpSession s){AppUser u=user(s);if(u==null)return unauthorized();String name=Optional.ofNullable(file.getOriginalFilename()).orElse("arquivo").replaceAll("[^a-zA-Z0-9._ -]","_");String ext=name.contains(".")?name.substring(name.lastIndexOf('.')+1).toLowerCase():"";String status=BLOCKED.contains(ext)?"BLOCKED":file.getSize()>20_000_000?"BLOCKED":"CLEAN";d.save("ATTACHMENT",u.email,status,UUID.randomUUID().toString(),Map.of("originalName",name,"size",file.getSize(),"declaredMime",Optional.ofNullable(file.getContentType()).orElse("unknown"),"scanner","MOCK - substituir por integração antimalware real"));if(!status.equals("CLEAN"))d.audit(u.email,"FILE_BLOCKED","ATTACHMENT",null,name);return ResponseEntity.ok(Map.of("name",name,"status",status,"message",status.equals("CLEAN")?"Arquivo validado pelo pipeline demonstrativo.":"Arquivo bloqueado por segurança."));}
  private ResponseEntity<?> updateOwned(Long id,HttpSession s,String status,Map<String,Object> extra){AppUser u=user(s);if(u==null)return unauthorized();var o=d.records.findById(id);if(o.isEmpty()||(!o.get().owner.equals(u.email)&&!u.role.equals("ADMIN")&&!u.role.equals("DOCTOR")))return forbidden();var r=o.get();var p=d.payload(r);p.putAll(extra);r.payload=write(p);r.status=status;d.records.save(r);return ResponseEntity.ok(row(r));}
  private String write(Object x){try{return d.json.writeValueAsString(x);}catch(Exception e){throw new IllegalArgumentException(e);}}
  private AppUser user(HttpSession s){Object id=s.getAttribute("uid");return id instanceof Long?d.users.findById((Long)id).orElse(null):null;}
  private ResponseEntity<?> unauthorized(){return ResponseEntity.status(401).body(Map.of("message","Sessão expirada."));} private ResponseEntity<?> forbidden(){return ResponseEntity.status(403).body(Map.of("message","Você não tem permissão para esta ação."));}
  private String mapType(String x){return switch(x){case "appointments"->"APPOINTMENT";case "tickets"->"TICKET";case "campaigns"->"CAMPAIGN";case "consents"->"CONSENT";case "audits"->"AUDIT";case "notifications"->"NOTIFICATION";default->x.toUpperCase();};}
  private List<Map<String,Object>> rows(String t,String owner){return (owner==null?d.records.findByTypeOrderByCreatedAtDesc(t):d.records.findByTypeAndOwnerOrderByCreatedAtDesc(t,owner)).stream().map(this::row).toList();}
  private Map<String,Object> row(DomainRecord r){Map<String,Object> m=new LinkedHashMap<>(d.payload(r));m.put("id",r.id);m.put("type",r.type);m.put("owner",r.owner);m.put("status",r.status);m.put("reference",r.reference);m.put("createdAt",r.createdAt);return m;}
  private Map<String,Object> userView(AppUser u){return Map.of("id",u.id,"name",u.name,"email",u.email,"role",u.role,"status",u.status,"permissions",u.permissions,"createdAt",u.createdAt);}
}
